services:
  # ---------- Databases ----------
  user-postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${USER_DB_USER:-user_user}
      POSTGRES_PASSWORD: ${USER_DB_PASS:-user_password}
      POSTGRES_DB: ${USER_DB_NAME:-user_db}
    ports:
      - "5433:5432"
    volumes:
      - user_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  product-postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${PRODUCT_DB_USER:-product_user}
      POSTGRES_PASSWORD: ${PRODUCT_DB_PASS:-product_password}
      POSTGRES_DB: ${PRODUCT_DB_NAME:-product_db}
    ports:
      - "5434:5432"
    volumes:
      - product_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  payment-postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${PAYMENT_DB_USER:-payment_user}
      POSTGRES_PASSWORD: ${PAYMENT_DB_PASS:-payment_password}
      POSTGRES_DB: ${PAYMENT_DB_NAME:-payments}
    ports:
      - "5435:5432"
    volumes:
      - payment_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok' localhost:27017 | grep 1"]
      interval: 10s
      timeout: 10s
      retries: 10

  # ---------- Messaging ----------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      # interno (containers): kafka:9092
      - "9092:9092"
      # externo (host): localhost:29092
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # listeners: interno e externo
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # UI: http://localhost:15672 (guest/guest)
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}

  # ---------- Microservices ----------
  user-service:
    build:
      context: ./user-service
    ports:
      - "8001:8000"
    environment:
      POSTGRES_HOST: user-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${USER_DB_NAME:-user_db}
      POSTGRES_USER: ${USER_DB_USER:-user_user}
      POSTGRES_PASSWORD: ${USER_DB_PASS:-user_password}
    depends_on:
      user-postgres:
        condition: service_healthy

  product-service:
    build:
      context: ./product-service
    ports:
      - "8002:8000"
    environment:
      DB_HOST: product-postgres
      DB_PORT: 5432
      DB_NAME: ${PRODUCT_DB_NAME:-product_db}
      DB_USER: ${PRODUCT_DB_USER:-product_user}
      DB_PASS: ${PRODUCT_DB_PASS:-product_password}
    depends_on:
      product-postgres:
        condition: service_healthy

  order-service:
    build:
      context: ./order-service
    ports:
      - "8003:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: ${ORDER_MONGO_DB:-orders_db}
      MONGO_COLLECTION: ${ORDER_MONGO_COLLECTION:-orders}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: ${KAFKA_TOPIC:-order-payments}
    depends_on:
      mongo:
        condition: service_healthy
      kafka:
        condition: service_started

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "8004:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://${PAYMENT_DB_USER:-payment_user}:${PAYMENT_DB_PASS:-payment_password}@payment-postgres:5432/${PAYMENT_DB_NAME:-payments}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: ${KAFKA_TOPIC:-order-payments}
      KAFKA_GROUP_ID: ${PAYMENT_KAFKA_GROUP:-payment-service}
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:5672/
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE:-payment-notifications}

    depends_on:
      payment-postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      rabbitmq:
        condition: service_started
  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/
      NOTIFICATION_QUEUE: payment-notifications
    depends_on:
      - rabbitmq
    restart: unless-stopped

volumes:
  user_pg_data:
  product_pg_data:
  payment_pg_data:
  mongo_data:
